version: '3.7'

services:
    database:
        image: postgres # use the latest
        env_file:
            - database.env
        volumes:
            - /var/lib/postgresql/data/ #persist data even if container shuts down
        restart: on-failure

    web:
        depends_on:
            - database
        build: .
        volumes:
            - .:/SingleViewApp
        ports: 
            - "8000:8000"
        environment:
            - HOSTNAME=database
        command: python manage.py runserver 0.0.0.0:8000
        restart: on-failure
        